k8snetworkplumbingwg/kubemacpool

- config/default/manager/manager.yaml
- config/default/rbac/rbac_role.yaml
- config/release/kubemacpool.yaml
- config/release/manager_image_patch.yaml
- config/test/kubemacpool.yaml
- config/test/manager_image_patch.yaml
- pkg/webhook/pod/pod.go
- pkg/webhook/virtualmachine/virtualmachine.go
- pkg/webhook/webhook.go
Change to replica to one, by using a label to ignore the webhook.
`kubemacpool/ignoreAdmission: "true"`
> Change to a deployment kind for the manager.

- pkg/pool-manager/pool.go
move the getNextMac function from start of the loop to the end.
> Use the first mac in the range

- doc/design.md
Add design document into the repo.
> Add design document

- pkg/pool-manager/pool.go
If we allocate a mac address then release it and immediately allocate the same one to another object
we can have issues with dhcp and arp discovery
This commit moves to the next valid mac address after we find a free one.
> Move to the next mac after we found a free one

- cmd/manager/main.go
- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
- pkg/pool-manager/pool.go
Changes:
START_POOL_RANGE -> RANGE_START
END_POOL_RANGE -> RANGE_END
> Rename the ranges variables

- pkg/pool-manager/pod_pool.go
- pkg/pool-manager/pool_test.go
- pkg/webhook/pod/pod.go
This PR fix an issue with requested networks.
Before this PR networks with requested mac where not added into the generated annotation.
> Fix pod annotation clear

- pkg/webhook/virtualmachine/virtualmachine.go
Related to https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/34
There was an issue when rebasing the previews PR this commit was removed
> Add update handler for virtual machines objects

- tests/virtual_machines_test.go
move a comment for test ID
related to https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/30#discussion_r297519047
> func test small nit

- pkg/pool-manager/pod_pool.go
- pkg/pool-manager/pool.go
there is no need for this map anymore
so in this PR we delete it.
> delete redundant vmToMacPoolMap

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
This PR reduce the amount of memory and also cpu requested by the manager.
> Reduce the amount of memory and cpu the manager request

- tests/virtual_machines_test.go
add testID to the failed yaml vm-test.
> add testID to failed yaml test

- tests/virtual_machines_test.go
test that when a VM NIC is remmoved , it's
mac address is released and can be used as
a custom mac for another VM configuration.
> test mac release after NIC deletion

- tests/virtual_machines_test.go
add test id to the NIC deletion test
> add test-ID

- Dockerfile
- PROJECT
- README.md
- cmd/manager/main.go
- hack/run.sh
- pkg/controller/add_pod.go
- pkg/controller/add_virtualmachine.go
- pkg/controller/controller.go
- pkg/controller/pod/pod_controller.go
- pkg/controller/virtualmachine/virtualmachine_controller.go
- pkg/manager/leaderelection.go
- pkg/manager/manager.go
- pkg/pool-manager/pool_test.go
- pkg/webhook/add_pod.go
- pkg/webhook/add_virtualmachine.go
- pkg/webhook/pod/pod.go
- pkg/webhook/virtualmachine/virtualmachine.go
- pkg/webhook/webhook.go
- tests/tests.go
- tests/tests_suite_test.go
- tests/virtual_machines_test.go
Change org name from K8sNetworkPlumbingWG to k8snetworkplumbingwg
> Lower case

- Makefile
- hack/install-go.sh
- tests/tests.go
In order not to get different results on different systems, let's include
specific Go binary under the project with custom GOROOT.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
> include go in the project

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
cherry picking the [`add labels` PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/96)  to release-v0.8 branch
> add label to kubemacpool yamls

- tests/virtual_machines_test.go
The finalizers update happens in the reconcile loop,
in the kubemacpool controller.
If during the finalizers-update, the object (the vm in this case)
was updated by another controller and a newer version of the object
was inserted to the database, the finalizers update will fail,
as it appears in the issue(https://github.com/k8snetworkplumbingwg/kubemacpool/issues/103) description,
and a new update attempt will be performed in the next reconcile iteration.
This will continue until the update will succeed and the finalizers will be updated.
since this update can take time we should wait for some reasonable time before failing the test.
Signed-off-by: alonSadan <asadan@redhat.com>
> Add Eventually to finalizers test

- OWNERS
Signed-off-by: Or Mergi <ormergi@redhat.com>
> Add Or Mergi as reviewer

- pkg/names/names.go
- pkg/pool-manager/pool.go
- pkg/pool-manager/pool_test.go
- pkg/pool-manager/virtualmachine_pool.go
- tests/virtual_machines_test.go
This is a backport to issue #114 on sharding branch (using rebase)
Signed-off-by: Or Mergi <ormergi@redhat.com>
> Ensure there are no VM's before test suite and each test (#114)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
They will add instructions to fill them in.
Signed-off-by: Quique Llorente <ellorent@redhat.com>
> Add PR/Issues templates

- README.md
Currently there is no documentation of how to disable kubemacpool on a specific namespace.
In this we will add proper documentation of this. 
```release-note
NONE
```
> adding documentation as to how to enable/disable opt-in of kubemacpool in a namespace

- .github/PULL_REQUEST_TEMPLATE.md
Let's make life better for all of us. Some of these issues repeat over
and over. If all contributors follow these rules, we can focus on
important stuff.
```release-note
NONE
```
> oath of a contributor

- pkg/manager/manager.go
- pkg/webhook/webhook.go
There were some old code from where KMP was creawting webhook configuration and
services so it was setting the ownership there, now that this is done by CNAO
this does not have to be done, so we prevent ownership stealing from CNAO.
```release-note
NONE
```
> Remove ownership stealing code

- README.md
- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
- tests/pods_test.go
- tests/virtual_machines_test.go
we want to change the label default value to 'allocate'. We also update the documentation.
```release-note
NONE
```
> Change opt in label default value to allocate

- pkg/controller/virtualmachine/virtualmachine_controller.go
- pkg/pool-manager/virtualmachine_pool.go
when creating and deleting multiple vms we may encounter conflict when updating the configmap and the vm instance.
In order to properly handle these conflict, we introduce the retryOnConflict method.
```release-note
NONE
```
> adding retryOnConflict methods to protect from conflicts

- Makefile
- automation/check-patch.e2e-k8s.sh
- go.mod
- go.sum
- hack/functest.sh
- tests/tests_suite_test.go
- vendor/kubevirt.io/qe-tools/LICENSE
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
- vendor/modules.txt
With this failure test cases are shown at prow as a table and is possible
to use polarion to match test plans
```release-note
NONE
```
> Add junit and polarion test reporters

- README.md
The ' is evaluated by the syntax highlighter as beginning of a string
and that breaks the highlighting in the whole example.
```release-note
NONE
```
> fix shell formatting of external cluster example

- automation/openshift.cnv.tier1.sh
- go.mod
- go.sum
- tests/virtual_machines_test.go
They are needed to filter correctly the test from polarion test plan and also dump
polarion xml.
```release-note
NONE
```
> Add polarion test_id flags

- build/Dockerfile
This PR change manager container base image to ubi8-minimal, this micis rhel8 containers and reduce container size.
```release-note
Moved to ubi8-minimal base container.
```
> Ubi8 minimal

- pkg/manager/leaderelection.go
In a case where an election is lost and the pod does require restart - we need to make sure that the we have only 1 leader pod label.
```release-note
NONE
```
> remove old leader labels  after leader election has been won.

- pkg/pool-manager/pool_test.go
- pkg/pool-manager/virtualmachine_pool.go
This is a manual cherry-pick of #188 
```release-note
NONE
```
> [Release v0.14.0] fix cache race

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
Dealing with leader elections forces us to start to play with maxUnavailable and friends
we are good we a simple Recreate.
```release-note
Change deployment strategy to `Recreate`
```
> Change deployment strategy to Recreate

- automation/check-patch.e2e-k8s.sh
- go.mod
- go.sum
- tests/tests_suite_test.go
- vendor/kubevirt.io/qe-tools/LICENSE
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
- vendor/modules.txt
This is a backport from https://github.com/k8snetworkplumbingwg/kubemacpool/pull/156
```release-note
NONE
```
> Add junit polarion reporter

- hack/functest.sh
It's almost impossible to pass correctly that field since it contains sub arguments, although
this is not the most clean solution it works and if var is empty it works too.
```release-note
NONE
```
> Use a env var for polarion '--test-suite-params'

- pkg/manager/leaderelection.go
in updateLeaderLabel both remove and add leader-labels.
We want to separate this since we that List might not contain the running pod.
Also, we remove unneeded use of kubeClient.Get that is already received in kubeClient.List().
```release-note
NONE
```
> separate label update in updateLeaderLabel

- pkg/utils/utils_suite_test.go
- pkg/utils/utils_test.go
- tests/virtual_machines_test.go
fix code format issues
```release-note
NONE
```
> fix code format issues

- Makefile
In case one want to map between master commit ids and a docker hub container tagging
the images with `git describe --tags` will allow that.
```release-note
Tag master pushed containers with `git describe --tags` output
```
> Add container push tag with `git describe --tags` output 

- Makefile
Depending on git version the `git describe --tags` has different commit id size
to ensure that is always the same we can specify `--abbrev=8` to ensure that
it uses 8 chars.
```release-note
NONE
```
> Ensure that the IMAGE_GIT_TAG has 8 chars at commit id

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
This PR adds pod description to kubemacpool pod
```release-note
NONE
```
> add pod description to kubemacpool pod

- tests/virtual_machines_test.go
This PR adds more information to investigate a flaky CI reported in #249
CNAO tier1 tests discovered a flaky test
Added a description to make the test fail
reason clearer.
```release-note
NONE
```
> ci, Add Expect description in flaky test

- pkg/webhook/pod/pod.go
- pkg/webhook/virtualmachine/virtualmachine.go
Currently kubemacpool webhook handlers patch the entire request object
(pod/virtualMachine). But sometimes there are changes made by other webhooks
or from internal kubernetes changes, that we don't want to set in our webhook.
In order to only add the wanted changes,
we change our webhook patch strategy to only patch the relevant changes.
```release-note
NONE
```
> webhook Handle, patch only kubemacpool changes

- tests/virtual_machines_test.go
This PR cleans the vm tests a little bit.
```release-note
NONE
```
> Refactor vm tests

- tests/tests.go
This PR adds a print of deployment in case of timeout of change replicas 
```release-note
NONE
```
> ci, add deployment print upon changeReplicas failure

- config/default/kustomization.yaml
- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
When Deployments are upgraded they cannot change matchingLabels since
they are inmutable, this change remove the problematic label from
matchingLabels.
```release-note
NONE
```
> Remove "app" from matchingLabels

- tests/tests.go
Changing Deployment replicas to restart KMP does not work well with CNAO
tier1 tests since CNAO will Reconcile the Deployment after changing the
replicas so it's not always working. This change replace the restart
mechanism with KMP pods deletiong and deployment condition check.
```release-note
NONE
```
> Delete pods to restart KMP

- pkg/manager/manager.go
This PR fixes a bug where if kuevirt is ready after KMP, then KMP will not relaod and as a result the VM controller will not be initiated.
- ***fix kubemacpool relaod if controller-manager returns***
currently kubemacpool is waiting on signals in order to reload the
manager, simulating a kubemacpool restart.
An example is if kubevirt is not ready by the time kubemacpol is up.
In the example - when kubevirt is ready, a channel is closed to signal
kubemacpool to restart.
This commit fixes the waitForSignal method to use the new context based
cancel function.
```release-note
NONE
```
> fix relaod if controller-manager.Start() returns

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
- pkg/pool-manager/pod_pool.go
This PR is a manual cherry-pick of https://github.com/k8snetworkplumbingwg/kubemacpool/pull/296
```release-note
NONE
```
> [release-v0.21] initPodMap, Limit podList request to avoid memory max limit

- pkg/pool-manager/virtualmachine_pool.go
limit the memory consumption when kubemacpool initiates the vm mac map
by limiting the request to chunks of 100 vms.
```release-note
NONE
```
> initVirtualMachineMap, Limit vmList request to avoid memory max limit

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
- pkg/pool-manager/pod_pool.go
This PR reverts commit db6d64e8027e319420ad167bafefd930761bc410.
This commit will later be replaced by only the limit removal
```release-note
NONE
```
> [release-v0.21] Revert pod pagination and limit removal

- tests/certificates_test.go
PR to upgrade to admissionregistration.v1 when running certificate related CI
```release-note
NONE
```
> ci, upgrade to admissionregistration.v1 on certs tests

- config/default/manager/manager.yaml
- config/release/kubemacpool.yaml
- config/test/kubemacpool.yaml
Cherry-pick of
https://github.com/k8snetworkplumbingwg/kubemacpool/pull/319
https://github.com/k8snetworkplumbingwg/kubemacpool/pull/320
Add minimum cpu and memory requests for KMP containers
```release-note
None
```
> [Release-v0.26] resources, Update minimum cpu / memory requests

- go.mod
- go.sum
- vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
- vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
- vendor/modules.txt
bump kube addmission 0.12.1
```release-note
NONE
```
> [release-v0.21] bump kube addmission 0.12.1

- pkg/pool-manager/pool_test.go
- pkg/pool-manager/virtualmachine_pool.go
When applying a VM with multiple interfaces with the same name,
the VM is rejected but kubemacpool is mishandling the MACs,
causing a side effect where that MAC is no longer usable (it
is "taken" by the ghost VM).
This commit fixes this by checking and rejecting VMs with
duplicate interface names on kmp webhook context.
```release-note
Kubemacpool webhook behavior is changed: virtualMachine with duplicate interface names will be rejected from now on.
```
> vm-pool, Reject VMs with duplicate interfaces

- OWNERS
This PR adds Add rhrazdil as reviewer 
```release-note
NONE
```
> OWNERS, Add rhrazdil as reviewer

- Makefile
- cluster/cluster.sh
- hack/common.sh
- hack/run.sh
Support (rootfull) podman OCI
Auto detect running OCI
Bump kubevirtci to have podman support
```release-note
None
```
> oci: Support podman

- Makefile
- hack/bump-kubevirtci.sh
Built such that automation can use it:
In case fatal happens return error code.
In case all is good, determine if there was a change
according non empty stdout.
```release-note
None
```
> kubevirtci: Introduce bump script

- go.mod
- go.sum
- vendor/github.com/emicklei/go-restful/.travis.yml
- vendor/github.com/emicklei/go-restful/CHANGES.md
- vendor/github.com/emicklei/go-restful/Makefile
- vendor/github.com/emicklei/go-restful/README.md
- vendor/github.com/emicklei/go-restful/container.go
- vendor/github.com/emicklei/go-restful/cors_filter.go
- vendor/github.com/emicklei/go-restful/jsr311.go
- vendor/github.com/emicklei/go-restful/parameter.go
- vendor/github.com/emicklei/go-restful/request.go
- vendor/github.com/emicklei/go-restful/response.go
- vendor/github.com/emicklei/go-restful/route.go
- vendor/github.com/emicklei/go-restful/route_builder.go
- vendor/github.com/emicklei/go-restful/route_reader.go
- vendor/github.com/emicklei/go-restful/service_error.go
- vendor/github.com/emicklei/go-restful/web_service.go
- vendor/modules.txt
CVE-2022-1996
```release-note
None
```
> [release-0.40] CVE-2022-1996: Bump github.com/emicklei/go-restful

- pkg/gauges/gauges.go
- pkg/manager/manager.go
Fix LICENSE format issue reported by `make fmt` 
```release-note
NONE
```
> fmt: Fix LICENSE format

- renovate.json
This PR adds new stable branches to the renovate bot
```release-note
NONE
```
> renovate: Expand to all stable branches

- README.md
> readme: Add content about metrics

- .golangci.yml
- Makefile
- tests/certificates_test.go
- tests/pods_test.go
- tests/tests.go
- tests/tests_suite_test.go
- tests/virtual_machines_test.go
This PR expands the linter coverage to the entire tests folder.
Assisted by Claude (Anthropic AI Assistant)
```release-note
NONE
```
> tests: Add linter coverage

- automation/check-patch.e2e-k8s.sh
- cluster/cluster.sh
- hack/bump-kubevirtci.sh
Soon we are switching to flannel instead Calico,
before that, lets update kubevirtci to see all is well with current latest kubevirtci.
```release-note
None
```
> Bump Kubevirtci
