pkg/webhook/webhook.go
Change the webhook port from 443 to 8000.
This change allows the controller to run without any special scc configuration
=> Fix openshift

cluster/sync.sh, cmd/manager/main.go, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/webhook/webhook.go
This way when we remove the statefulset the webhook will be removed as well.
This PR also change the name of the hook from `mutating-webhook-configuration` to `kubemacpool`
This should fix https://github.com/kubevirt/cluster-network-addons-operator/issues/33
=> Add owner reference for the mutating webhook

cmd/manager/main.go, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/manager/internal.go, pkg/manager/manager.go, pkg/manager/recorder/recorder.go
Copy the manager code from controller runtime and change it.
With the new manager the controller will became ready only when it became leader.
most of the code is the same as the regular manager I just change the leader election function.
When a controller take the leader he also create a file under `/tmp/healthy` this way the pod will became ready.
When the pod became ready it will be added as an endpoint for the admission webhook service
=> Allow to run multiple replicas

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
For large cluster the kubemacpool gets kill by OOM.
=> Update resource limit and request

pkg/pool-manager/pod_pool.go
This PR fix an issue when initializing the mac address maps.
The problem was that when we init the pod mac we didn't check if the pod is related to kubevirt virtual machine object.
If it is we skip it and let the vm initialization function to handle it.
=> Fix init function for pod to skip kubevirt vm objects

pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/virtualmachine_pool.go
This PR allow to revert allocations if there was a problem allocating one of the interfaces.
The allocation could fail if there is not enough free mac addresses in the pool for all the interfaces, if the user request a mac that is already allocated or invalid.
=> Revert mac allocation

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
We don't need this any more after chainging the manager to one replica
=> Remove the readinessProbe

pkg/webhook/virtualmachine/virtualmachine.go
If the vm object doesn't have a namespace variable we take the namespace from the request and add it to the vm object.
=> Add namespace to vm object if not exist

pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
Add virtual machine update webhook
Add update handler for virtual machines objects.
This PR fix an issue when the user try to apply the same vm again.
Before this PR if the issue apply the yaml file again the mac addresses allocated by the kubemacpool will disapear from the vm object.
We support now to apply the same yaml again and all the allocated addresses will be reserved but also add and remove interfaces.
=> Fix multiple yaml apply

tests/virtual_machines_test.go
- add test that check if kubemacpool releases the mac address
after aplying a failed yaml
*curretly the test is pending until the issue is fixed
=> add test for mac address release-FAILS

config/default/kustomization.yaml, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/webhook/webhook.go
This PR change the cert creation mode from secret to file system.
This way the pod will not make a restart in the first time.
=> Change Cert to file system mode

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
A test for  the function checkCast(), which is used when creating
a new pool manager to verify that the first octet of the ranges
is 02,06,0A or 0E.
=> Test for unicast validation

cmd/manager/main.go, pkg/manager/manager.go
This PR change the manager to reload when kubevirt is found
instead of reseting the pod
Before this PR if we deploy kubemacpool before kubevirt we start
a check loop for the virtual machine CRD and when we found it we
restart the kubemacpool pod to load the new watch controller.
=> Reload instead of restart

cmd/manager/main.go, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/manager/leaderelection.go, pkg/manager/manager.go, pkg/manager/recorder.go, pkg/webhook/webhook.go, tests/tests.go, tests/virtual_machines_test.go
This PR allow to run the kubemacpool manager with multiple replicas
When a manager become leader it updates is pod label to a leader.
This label is the selector of the webhook service.
This way the service will always point only to the leader manager.
=> Allow mutiple replicas for manager

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, pkg/utils/utils.go, pkg/webhook/virtualmachine/virtualmachine.go, tests/tests_suite_test.go, tests/virtual_machines_test.go
In this PR we added a feature of finalizers ,which allow us a more safe way of deleting VMs
and releasing their mac.
The finalizers do not allow the object to be deleted until some necessary actions occur. in our
case- the release of the mac address.
Before this PR, the release of the mac and the deletion of the VM were not dependent,
so in order to keep track with the allocated mac addresses and safely release them,
we mapped each mac address to the name of the object it was allocated for (pod or VM).
That implementation could lead to safety issues. For example, if the controller collapses for some reason,we lose track of the allocated macs.
With the finalizers, we can be sure that before any deletion of a VM it's mac will be released, and tracking the allocated mac addresses is done …
=> add finalizers to allow deep delete of VMs

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
we added a pod-anti-affinity to the kubemacpool pod spec which constrain
(in a *soft way) the scheduling of the pod so that
no more than one kubemacpool-pod will be scheduled on a single node.
*if there is no other choice, it will bypass the constraint,
and will create more than one kubemacpool pods on a single node.
=> add affinty to constrain kubemacpool pods

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
add pod disruption budjet to kubemacpool to set
the minimum number of available kubemacpool pods
on one node to 1 (on volentary distruption)
=> add pod disruption budget to kubemacapool

pkg/manager/leaderelection.go, pkg/manager/manager.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/webhook.go, tests/tests.go
This PR allow to run the kubemacpool in a different namespace
not hard coded one.
The manager reads the pod namespace and use it to create the
webhook and service.
=> Allow to run kubemacpool in different namespace

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/manager/leaderelection.go, pkg/manager/manager.go, pkg/names/names.go, pkg/pool-manager/pool.go, pkg/pool-manager/virtualmachine_pool.go, tests/tests_suite_test.go
This PR fix an issue we have when we create the kubemacpool before
kubevirt was installed and then we try to restart the manager after
we find kubevirt in the cluster.
The manager was stuck waiting to be the leader (but it's already
the leader)
/cc @alonSadan
=> Fix mutiple replica code

tests/virtual_machines_test.go
In this PR we fix styling issues in
the VM-tests.
in this PR I changed Should(not(..))
to ShouldNot(...).
Feel free to suggest more fixes in the
comments so I can fix them in this PR
or open a different PR for them.
=> Fix styling issues in VM-tests

pkg/webhook/pod/pod.go, tests/virtual_machines_test.go
We are still facing many issues with inaccessible webhook blocking
creation of VMs and especially pods. Let's make our failure policy
ignore for now and investigate mentioned issues only in test
environments for now.
=> set webhooks failure policy to Ignore

cmd/manager/main.go, pkg/manager/manager.go, pkg/webhook/webhook.go
This PR creates a OwnerRef for the manager service.
When the manager deployment will be removed it will also remove the service.
Before this PR if we remove the deployment it will not remove the service
related to him.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/k8snetworkplumbingwg/kubemacpool/71)
=> Create a ownerRef for the service

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/names/names.go, pkg/webhook/pod/pod.go, pkg/webhook/webhook.go, tests/pods_test.go, tests/tests.go
This PR fix the issue when a Critical pod like the sdn provider
need to be recreated.
change the mutating webhook to skip namespaces to contains
1. runlevel=[0,1] for kubernetes environments
2. openshift.io/run-level=[0,1] for openshift environments
With this change we can change the FailurePolicy from ignore to fail.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/k8snetworkplumbingwg/kubemacpool/74)
=> Skip pods in critical namespaces

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
This PR fix the port in the manager yaml.
Change from 9876 to 8000
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/k8snetworkplumbingwg/kubemacpool/76)
=> Update the port number in the manager deployment

pkg/webhook/virtualmachine/virtualmachine.go, tests/tests.go
With https://github.com/k8snetworkplumbingwg/kubemacpool/pull/74
we set webhook failing policy to failing in belief the kubemacpool
became stable. Unfortunatelly, we still see some certificate issues
as listed in https://bugzilla.redhat.com/1779513 (most probably due to
ca rotation).
The policy is moved back to failing till the issues are fixed.
The fixes will be tracked in - https://bugzilla.redhat.com/1787213
Signed-off-by: Alona Kaplan <alkaplan@redhat.com>
=> BZ1779513: make webhook ignoring

automation/check-patch.e2e-k8s.sh, automation/check-patch.setup.sh, automation/check-patch.unit-test.sh
These can be used to run unit/functional tests on an arbitrary host
with docker and rsync installed. They will be later used for CI triggered
by prow.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
=> add automation scripts

.travis.yml, Makefile, hack/test.sh
We can run the tests with Go alone, there is no need to containerize them.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
=> drop dockerized test

Makefile, automation/check-patch.e2e-k8s.sh, automation/check-patch.setup.sh, automation/check-patch.unit-test.sh, cluster/sync.sh, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/release/manager_image_patch.yaml, config/test/kubemacpool.yaml, config/test/manager_image_patch.yaml, hack/docker-image/Dockerfile, pkg/manager/manager.go, tests/tests.go, tests/virtual_machines_test.go, vendor/modules.txt
Currently, manager pods turn Ready as soon as their binary starts.
However, it takes ~40 more seconds for the webhook to actually start
serving requests. In order to avoid that, we introduce a readiness
probe that marks the pod as Ready only once the server starts.
=> adding a readiness probe to kubemacpool pods

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
There is a label missing from kubemacpool yamls: app: kubemacpool
This label is used in various places like rotate_cert script in [HCO](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/tools/rotate-certs.sh#L39).
=> add label to kubemacpool yamls

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/names/names.go, pkg/webhook/webhook.go, tests/pods_test.go, tests/tests.go
This PR fix the issue when a Critical pod like the sdn provider
need to be recreated.
change the mutating webhook to skip namespaces to contains
1. runlevel=[0,1] for kubernetes environments
2. openshift.io/run-level=[0,1] for openshift environments
With this change we can change the FailurePolicy from ignore to fail.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
=> [release-v0.8] Skip pods in critical namespaces

tests/virtual_machines_test.go
Most of the kubemacpool tests are using 'Eventually' method.
Using this method may hide bugs (for [example](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/83)).
In this PR we will reexamine the use of eventually in the e2e tests, to achieve the following goal:
1. remove eventually when is not needed.
2. in places where eventually is needed, strive to make it as specific as possible by adding "Expect" method for the specific error we are expecting to get while failing.
As part of opening this PR, we will signal as 'P' tests that show unstable behavior as a result of the removal of eventually - indicating a potential bug. For each there will be opened a corresponding issue.
=> reducing amount of "eventually"s in e2e tests

tests/virtual_machines_test.go
As part of the [PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/100) and in an effort to make the tests more reliable, we skipped a few tests for future handling. 
This PR fixed [issue 99](https://github.com/k8snetworkplumbingwg/kubemacpool/issues/99) in test #2995 
=> fix reuse released MAC test #2995

tests/virtual_machines_test.go
As part of the [PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/100) and in an effort to make the tests more reliable, we skipped a few tests for future handling. 
This PR fixed [issue 102](https://github.com/k8snetworkplumbingwg/kubemacpool/issues/102) in test #2243
=> fix re-apply test #2243

config/default/manager/manager.yaml, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/release/manager_image_patch.yaml, config/test/kubemacpool.yaml, config/test/manager_image_patch.yaml, pkg/names/names.go, pkg/webhook/webhook.go, tests/tests.go
This PR change the deployment strategy from deploying kubemacpool-mac-controller-manager pod with Deployment to StatufSet.
As part of removing the leader-election mechanism effort #109 , it is necessary to enumerate the `kubemacpool-mac-controller-manager` pod names, with StatfulSet it is out-of-the-box functionality.
Signed-off-by: Or Mergi <ormergi@redhat.com>
=> Deploy kubemacpool-mac-controller-manager with StatefulSet

cluster/kubevirtci.sh
This PR bumps kubevirtci to latest commit,
Includes using calico cni instead of flannel.
Signed-off-by: Or Mergi <ormergi@redhat.com>
=> Bump kubevirtci

automation/check-patch.e2e-k8s.sh, cluster/kubevirtci.sh
It also make possible to specify different KUBEVIRT_PROVIDER
Signed-off-by: Quique Llorente <ellorent@redhat.com>
=> Remove 1.17.0 provider reference

config/default/manager/manager.yaml, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/controller/pod/pod_controller.go, pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/names/names.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/virtualmachine_pool.go, tests/pods_test.go, tests/tests.go, tests/virtual_machines_test.go
Currently the kubemacpool operate on all non-critical namespaces by default.
We want to invert this behavior to opt-in: only namespaces that state the kubemacpool label would be served by the kmp.
In this PR we will add namespace selector to the mutating webhook manifest, and also to the controller reconcile logic. Additionally, the necessary changes will be made to tests, and other tests are added.
=> Add opt in functionality

README.md
Following the insertion of the new opt-in namespace behavior in kubemacpool, a change was added to the documentation.
=> adding proper documentation to operate kubemacpool opt-in new behavior

tests/pods_test.go
currently pod tests ignore 'connection-refused' errors. 
Following merge of #124 and in order to know better if we have these issues there, I would like to remove these ignores.
```release-note
NONE
```
=> DNF remove connection-refuse ignore in pod e2e tests

.travis.yml, Makefile, hack/check.sh
currently there is no check that makes sure that all generated manifests are committed.
In order to fix this we will add it in travis test like they do in [kubevirt](https://github.com/kubevirt/kubevirt/blob/6e87ec791e03fdb9899bbe85bbdd441a72c534ab/.travis.yml#L19).
```release-note
NONE
```
=> adding check that all genereated files are commited before performing automation tests

tests/virtual_machines_test.go
This PR remove Pending flag form 2162 and 2165 tests.
These tests were flaky due to an issue with how the manager pods
reported readiness, this caused the manager-pods to raise
`connection refused` errors right after deletion.
We deploy the manager pods with Deployment thus after deletion the pods 
will be be created again right away, and so are the certs by the cert-manager used
in KubeMacPollManager.
The manager-pods will report readiness before the certs are ready,
and eventually cause connection refused error (due to absent cert).
Now that #124 is merged we can continue to use these tests.
```release-note
NONE
```
=> Remove Pending flag from skipped tests

.gitignore, Makefile, README.md, cluster/clean.sh, cluster/sync.sh, cluster/up.sh, config/test/kustomization.yaml, config/test/manager_image_patch.yaml, hack/clean-ns-finalizers.sh, hack/functest.sh, hack/run.sh
Running latest kubemacpool at external cluster like openshift helps on iterating for defects, this PR add support for `KUBEVIRT_PROVIDER=external` and it will deploy and run functest on an external cluster pointed at with `KUBECONFIG`
Doing the following steps will will deploy kubemacpool + kubevirt + multus and wil
run functest towards it at an external cluster.
```
export KUBEVIRT_PROVIDER=external
export KUBECONFIG=[]/kubeconfig
export DEV_REGISTRY=docker.io
export REPO=$USER
export make cluster-up cluster-sync functest
```
The installed kubevirt and CNAO/multus is not cleaned up it can be put something in place at a follow up.
```release-note
Support for KUBEVIRT_PROVIDER=external
```
=> Enable cluster-sync with external provider

go.mod, go.sum, vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/secret.go, vendor/modules.txt
Bumps the webhook's library to deal with secrets ownership correctly so we can integrate with CNAO.
```release-note
kube-admission-webhook 0.7.0
```
=> Bump kube-admission-webhook 0.7.0

config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
The current kube-admission-webhook library does not use CSRs anymore
so RBAC is not needed.
```release-note
NONE
```
=> Remove CSR's related RBAC

README.md, tests/tests.go, tests/tests_suite_test.go, tests/virtual_machines_test.go
To run functest at HCO provided cluster we need to be able to change the namespace to map with clustern-network-addons-operator one and also filter pods by app=kubemacpool they don't mess with not kubemacpool pods
```release-note
NONE
```
=> Paramtereize manager namespaces used by functest

README.md, hack/clean-ns-finalizers.sh, tests/tests.go, tests/tests_suite_test.go
Instead of using MANAGER_NAMESPACE env var this search for pods with label `app=kubemacpool` and
use the namespace there.
```release-note
NONE
```
=> Parameterize manager namespace at tests from pods

tests/tests.go, tests/virtual_machines_test.go
Test were failing at CNAO looks like it takes more time to reach ready
state at manager pods after changing leardership, with this change
the test check not only that there is at pod with leadership  but also
that that pod is Ready.
```release-note
NONE
```
=> Check manager pod readyness changing leadership at test

cmd/manager/main.go, pkg/names/names.go, tests/tests.go, tests/virtual_machines_test.go
When a vm creation fails, the allocated mac stays in the configmap until a set wait-time - and then released in [vmWaitingCleanupLook() routine](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/2982d1a7646a75eab32fa0e831a7f81b643d8c6e/pkg/pool-manager/virtualmachine_pool.go#L436).
This wait-time is given as an argument to the kubemacpool container in the deployment manifest.
Specifically, the wait-time in production manifests is bigger than the time we wait for the vm to be released in tests.
In order to fix that, we now read the wait-time from kubemacpool deployment and consider it during the relevant tests.
```release-note
NONE
```
=> add additional wait time in tests that check failed vm creation scenarios

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
Currently it's hard to follow along the multiple reconcile logs, that sometimes reconcile the same vm (for example, a create followed by a update request).
In order to make it easier to follow the logs, we added a pseudo random "unique" ID, to be attached to the start of all relevant logs in reconcile. 
```release-note
NONE
```
=> adding reconcile request id to better track multiple thread logs

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Currently kubemacpool works in a active-backup approach, where the waiting pod is in not-ready state.
This can cause conflict when performing node drain, since we have kubemapool disruption pod budget set to minimum 1 ready pods.
In order to fix this, we need to remove the disruption pod budget, and return it only after we implement active-active approach in the kubemacpool pods
```release-note
NONE
```
=> remove disruption pod budget from kubemacpool

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/virtualmachine/virtualmachine.go, tests/virtual_machines_test.go
Currently when a vm is created the finalizer is added in the controller, allowing for a small window for the vm to be deleted before creation reconcile puts the finalizer.
This can result with a mac to not be released properly from the kubemacpool internal cache.
The situation occurs especially in tests when create vm and deletion is very quick, and there are retryOnConflicts
In order to fix this, we insert the finalizer during the webhook request initiated by the vm creation.
```release-note
NONE
```
=> moving finalizer addition to webhook

pkg/controller/virtualmachine/virtualmachine_controller.go, tests/virtual_machines_test.go
When a VM is created at an opt-in namespace and namespace is changed to
opt-out has to be possible to delete that VM. This PR try to delete finalizer and update
mac cache always independent of being at opt-in or not.
```release-note
Remove finalizer is independent of opt-in option.
```
=> Remove finalizer always

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
Currently it's hard to follow along the multiple reconcile logs, that sometimes reconcile the same vm (for example, a create followed by a update request).
In order to make it easier to follow the logs, we added a pseudo random "unique" ID, to be attached to the start of all relevant logs in reconcile.
Backported from https://github.com/k8snetworkplumbingwg/kubemacpool/pull/166
```release-note
NONE
```
=> [release-v0.14.0] adding reconcile request id to better track multiple thread logs (#166)

config/test/kubemacpool.yaml, config/test/kustomization.yaml, config/test/manager_image_patch.yaml, hack/functest.sh
wait-time is an argument passed by deployment to the kubemacpool manager pod.
When a vm is created but fails on a webhook that is not kubemacpool, then the mac should be retruned to the pool.
Since the kubemacpool controller cannot catch this cases, we use a goroutine thread that collects failed vms after the wait-time.
Currently we run on tests in a separate wait-time (10 seconds) than the one configured in production (10 min)
This can mask potential issues where the controller fails to do it's job from some reason, but the goroutine releases the mac and makes it look like all is good.
in order to run exactly as production, we want to change the wait-time to 10 mins - like in production.
This will cause …
=> aligning wait-time of test to those of production

go.mod, go.sum
It was pointing to a commit id for the 0.8.0 not the tag.
They are the same version just different name.
```release-note
NONE
```
=> Correct the kube-admission-webhook version at go.mod

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/manager/manager.go
Latst kubemacpool does not use controller-runtime healt probe since it's using
the one at kube-admission-webhook, so we can remove the HEALT_PROBE_X environment
variables.
```release-note
NONE
```
=> Remove HEALT_PROBE_HOST and HEALT_PROBE_PORT

tests/tests.go, tests/virtual_machines_test.go
Currently, there is no test checking that a vm that was created in kubemacpool pod leader is successfully migrated to a new leader should leadership change occurs.
This commit adds such a test.
```release-note
NONE
```
=> add collision detection test in leader change context.

cmd/manager/main.go, pkg/manager/manager.go
Currently in the main Run() method, we don't log error in case something fails.
We want to exit the Run() method should a irreconcilable error occur, and a proper log to be added in that case.
```release-note
NONE
```
=> add logs to document failing scenarios in kubemacpool startup.

pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
Currently, it's possible that the a webhook 1 will add a mac and wrongly re-insert it to the cache on controller reconcile if it was bypassed by a new webhook 2 deleting the macs. This would cause the belated controller to re-add the mac.
To fix it we add a check that the mac is not already deleted in the controller.
```release-note
NONE
```
=> fix race between webhook and controller

cluster/sync.sh, config/default/manager/manager.yaml, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/manager/leaderelection.go, pkg/manager/manager.go, pkg/names/names.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, tests/tests.go
manual cherry pick of #182 
```release-note
NONE
```
=> [Release v0.14.0] change leadership mechanism

pkg/pool-manager/pool_test.go
remove debug print merged by mistake in pool_test.go
```release-note
NONE
```
=> remove debug print

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/pool-manager/pool_test.go
Fixing BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1847594
We should not sneak into the restricted space.
```release-note
Drop runtime level label from Namespace
```
=> drop namespace annotations

pkg/manager/leaderelection.go, pkg/manager/manager_suite_test.go, pkg/manager/manager_test.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Currently, due to faulty labeling logic, if a pod won leadership twice it will loose it's leadership label.
This commit fixes that, and also adds unit tests to prevent this from happening.
```release-note
NONE
```
=> fix leadership label removed after twice winning election

pkg/manager/leaderelection.go, pkg/manager/manager_test.go
This PR update the `kubermacpool-leader` label only at pods with app=kubemacpool label, oherwise it iterate over all the pods at the same namespace, this is not a critical bug is kind of cosmetics but it reduce the time to update leader label.
```release-note
NONE
```
=> Update leader label only at pods with label 'app=kubemacpool'

config/test/kubemacpool.yaml, config/test/kustomization.yaml, config/test/manager_range_patch.yaml, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/utils/utils.go, pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go, tests/pods_test.go, tests/tests.go, tests/virtual_machines_test.go
Currently during each start of kubemacpool tier1 test, we perform an initilazaion of the mac-range configmap.
This ability is not supported outside of the kubemacpool standalone repo, and so it makes it a problem to run tier1 tests on CNAO (for example).
We would like to change the test behavior to stop using range change.
In order to do that, we will remove the mac range change, and instead change tests the check depleted mac pools, to allocate filler vms that will deplete the mac pool. Also, we will change the range in kubemacpool repo to 16 macs in the test manifest.
This way, if some external repo like CNAO wants to run teir1 tests, they can will skip these tests using the common phrase "mac-pool is …
=> Remove pod range change in tests

README.md
It is important to set a distinct seemingly-random range for each cluster.
If nearby clusters are deployed with the same range and using Layer 2 CNIs, inter-cluster collision would be likely.
This PR states this explicitly and provides bash code to do that. While at it, this PR also makes the relevant section more readable.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
```release-note
NONE
```
=> README: production user should change mac range

cluster/up.sh
Currently we're using a fixed version of kubevirt.
Lets move to use the latest z stram  release kubevirt release of a fixed major, and benefit from the bug improvements and featuresthat the latest stable release has to offer.
master branch can use fixed major-minor of v0.31. 
I think it's not very risky considering kubevirt's role in kubemacpool operation.
```release-note
use kubevirt latest release
```
=> move to use latest z stream kubevirt release

cluster/up.sh
This PR is a backport to #218 with the exception of setting the kuvevirt major_minor to 0.30 which is  the stabe branch
```release-note
NONE
```
=> [release-v0.14.0] Backport kubevirt to latest z stable

hack/cni-plugins/cni-plugins.yaml, hack/multus/multus.yaml
Currently kubemacpool contains manifests with daemonset with apiVersion extensions/v1beta1. We want to upgrade them to apps/v1.
fixes #221 
```release-note
NONE
```
=> update damonsets to apps/v1 in manifests

pkg/manager/manager.go
Let's add a wrapping function to catch the errs.
If an Error occur - also restart pod to initiate election.
```release-note
NONE
```
=> waitToStartLeading goroutine does not catch error.

go.mod, go.sum, pkg/webhook/webhook.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go, vendor/modules.txt
This PR bumps kube-admission-webhook library to 0.10.0 it add two features:
- A parameter to configure CA expiration time
- A overlap mechanism have multiple certificates at CA bundle
```release-note
Bump kube-admission-webhook to 0.10.0
```
=> Kaw 0.10.0

go.mod, go.sum, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go, vendor/modules.txt
It does not set ownership to TLS secrets
```release-note
Bump kube-admission-webhook to 0.11.0 (no owner at secret)
```
=> Bump kaw to 0.11.0

go.mod, go.sum, pkg/manager/manager.go, pkg/webhook/webhook.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go, vendor/modules.txt
This PR bumps the kube-admission-webhook to 0.12.0 It contains the knob CAOverlapInterval and also some refactorings on how the certificate options are passed to it.
```release-note
Bump kube-admission-webhook to 0.12.0
```
=> Kaw 0.12.0

README.md, cmd/manager/main.go, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/manager/manager.go, pkg/webhook/webhook.go
It will expose the following knobs to pod's environment variables:
- CARotateInterval -> CA_ROTATE_INTERVAL
- CAOverlapInterval -> CA_OVERLAP_INTERVAL
- CertRotateInterval  -> CERT_ROTATE_INTERVAL
The values at manifests are
- CA_ROTATE_INTERVAL -> One year
- CA_OVERLAP_INTERVAL -> One year
_ CERT_ROTATE_INTERVAL -> Half year
Signed-off-by: Quique Llorente <ellorent@redhat.com>
```release-note
Expose certificate handling knobs CA_ROTATE_INTERVAL, CA_OVERLAP_INTERVAL, CERT_ROTATE_INTERVAL
```
=> Expose kube-admission-webhook cert manager knobs as env vars

README.md, config/default/manager/manager.yaml, config/default/mutatepods_opt_in_patch.yaml, config/default/mutatepods_opt_out_patch.yaml, config/default/mutatevirtualmachines_opt_in_patch.yaml, config/default/mutatevirtualmachines_opt_out_patch.yaml, config/release/kubemacpool.yaml, config/release/kustomization.yaml, config/release/mutatepods_opt_mode_patch.yaml, config/release/mutatevirtualmachines_opt_mode_patch.yaml, config/test/kubemacpool.yaml, config/test/kustomization.yaml, config/test/mutatepods_opt_mode_patch.yaml, config/test/mutatevirtualmachines_opt_mode_patch.yaml, tests/tests.go, tests/virtual_machines_test.go
Currently, we have 2 mutating webhooks: mutatepods and mutatevirtualmachines.
Both work in opt-in mode, meaning kmp gives service only to pods/vms reside in namespace
that were specifically opted-in for it.
Lets reverse the behavior for vms and pods to opt-out.
a user that will want to be opted out will add the appropriate label
to his namespace.
In order to do that, we change the config manifest.
The mutatepod webhook will remain opt-in in release manifest
until it is more thoroughly tested and groomed.
For that, we add two kustomize patches to easily configure the mutatepod to opt-in/out
```release-note
Change mutatevirtualmachines to Opt-out in release manifests
```
=>  change kmp operation to opt-out

pkg/names/names.go, pkg/pool-manager/pool_test.go, tests/certificates_test.go
Currently the cert test uses specific manager namespace
that will only be correct if running on kubemacpool repo.
Let fix by using managerNamespace which gets the real namespace
from the cluster at  the beginning of the test suite.
```release-note
NONE
```
=> fix cert test to use manager namespace

tests/virtual_machines_test.go
This PR moves polarion tests to a new context, using the default opt-mode config
- **move test_id related tests to a new context**
Currently all 'test_id' test are performed in opt-out context
There is no specific reason they were put there, since
they can run on either opt-mode, as long as they are running
on the same opt-mode configured by the cluster configuration (in order to prevent
the oprator deploying kubemacpool to reconcile back from the opt-mode configured by the test).
Let's therefor move the tests to a new context that will run using the
default opt-mode config that is set on the cluster.
Also this commit includes a small format fix in AllocateFillerVms
- **add BeforeEach to opt-In test**
Since opt-mode contexts may run in different …
=> move 'test_id' tests to a new context, using the default opt-mode cluster config

README.md
=> fix internal anchor link to opt-in/out modes in README file

pkg/pool-manager/pool_test.go, tests/tests.go, tests/virtual_machines_test.go
Currently Context: "When Running with default opt-mode configuration"
is only working on opt-out mode.
We need to adjust the test namespace according to
the currently configured opt-mode configuration
```release-note
NONE
```
=> adjust test_id context to current opt-mode

go.mod, vendor/modules.txt
Before you click the 'Create pull request' make sure that:
- This PR introduces a single feature of fix, just one
- This PR does not leave the master branch broken
- Every commit in this PR has a commit message explaining what do you change,
why and what is the outcome
- If your change introduces a complex concept or a change to user interaction
with the project or the application, make sure to document it
If you don't comply with these rules, you waste your energy, time of reviewers
and cause suffering of future generations.
-->
Go crypto library for versions < 1.15 is not filling in the SKI field for CAs [1] so we bump to 1.15
[1] golang/go#26676
[2] https://go-review.googlesource.com/c/go/+/227098/
Signed-off-by: Quique Llorente …
=> Bump to go 1.15 to get SubjectKeyId at CA certificate

hack/functest.sh
When running kubemacpool tier1 in CNAO repo,
the test [panics](https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/655/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1326935780098052096), 
updated the functest flags.
changed timeout flag to test.timeout
removed no longer supported race flag
```release-note
NONE
```
=> functests, fix functests flags

hack/functest.sh
This PR reverts the former PR #251 that attempted to fix the go test flags.
Furthermore, it fixes the flags to git the correct order, now needed in golang1.15
- **Revert "functests, fix functests flags (#251)"**
- **functest, fix flags to git golang1.15 changes**
After a change dojne in golang1.15 [1],
go test flags should be as follows:
go test [test flags] [packages] [flags for test binary]
Changed go test flags to appear before package
[1] https://go-review.googlesource.com/c/go/+/14826/
```release-note
NONE
```
=> functest, Revert #251 and fix test flags

tests/virtual_machines_test.go
During test_id:2995 we allow getting an error saying that the mac
is still occupied until it is released by the controller.
The current error message is wrong, as the range is not full in this
specific test.
Fixed to the correct expected error.
```release-note
NONE
```
=> test 2995, Fix wrong expected error

pkg/pool-manager/pool_test.go
This PR adds a test to make sure KMP supports disk.io configuration on kubevirt
```release-note
NONE
```
=> disk.io, Add test to check disk.io configuration is presevred

tests/virtual_machines_test.go
Currently we're using gomega's error matcher to deep compare the error
struct. We are only insterested in comparing the error message.
Changed the error matcher to compare the error message.
```release-note
NONE
```
=> ci, Fix test_id:2995 error matcher check

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/virtualmachine/virtualmachine.go
In This PR I move some logs from `DEBUG` to `INFO` and vise versa. 
When running KMP from HCO/CNAO/CNV then only `INFO` logs are shown.
This change should make it easier for us to follow the KMP logs when in production environment.
- **logs, Make important logs more visible**
Currently it is not easy to understand the the logs when in production mode
Also, we keep a 3 second reoccurring log on production which is annoying.
Refactored the logs in order to give a good picture of what's happening in
production mode.
Moved the 3 second reoccurring log to be a debug log.
`logger.V(1).info` will result to a `DEBUG` log. `logger.info`, will appear as `INFO`
```release-note
NONE
```
=> logs, Make important logs more visible

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, tests/tests.go, tests/virtual_machines_test.go
currently vm controller reconcile checks opt-in case.
in case of vm creation in opt-out mode the vmWaitConfigMap is not cleared as
part of normal vm creation, and after 10 minutes will be removed from cache.
Added opt-mode check in vm reconcile
Added test in opt-in/out to make sure vmWaitConfigMap is working well.
```release-note
NONE
```
=> opt-out, Fix opt-out mode not updating configMap

pkg/pool-manager/virtualmachine_pool.go
During interface update, new macs are collected on newAllocations list.
in some situation, an empty mac is inserted, instead of the added mac.
Fixed to add the correct mac Address
Although we currently don't really use the newAllocations list in webhook update, it will be need in future design so better fix it now.
```release-note
NONE
```
=> webhook, Fix newAllocations list in webhook update

hack/functest.sh, pkg/controller/pod/pod_controller.go, pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/macentry.go, pkg/pool-manager/macentry_test.go, pkg/pool-manager/macpoolmap.go, pkg/pool-manager/macpoolmap_test.go, pkg/pool-manager/migratelegacyconfigmap.go, pkg/pool-manager/migratelegacyconfigmap_test.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/transaction.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/pod/pod.go, pkg/webhook/virtualmachine/virtualmachine.go, tests/tests.go, tests/virtual_machines_test.go
This PR introduces a major change in kubemacpool macpool structure and handling, to use timestamp and better handle the KMP webhook side effects. 
- **ci, Add now to macPool params**
Replaces time.Now() to use a configurable func var stored in macPool
interface.
Currently there is not difference in behavior due to this change, but in
the future this will allow us to run unit tests with mocked time.
- **webhook, Add kubemacpoolTransactionTimeStamp annotation**
Introduce a new annotation to the virtualMachine instance:
kubemacpool.io/transaction-timestamp. This annotation will hold the timestamp
when the webhook runs.
The annotation format will be RFC3339Nano which allows smaller granolarity and
also accepts the old RFC3339 format if parsing old …
=> Change macPoolMap to use transaction timestamps

pkg/controller/pod/pod_controller.go, pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, tests/virtual_machines_test.go
usually Kubemacpool handles only managed pods/vms according to the opt-mode. 
However there are corner cases (for example when initializing the macPoolMap for pods/vms) where we don't consider if the pods/vms are managed.
This PR addresses this issue to only handle managed instances.
- **opt-mode, generalize pods and vms to use the same opt-mode check**
Currently pod and vm handlers use slightly different functions to
determine if the pod/vm namespace is handled by kubemacpool according to
the opt-mode.
Aligned them to use the same function
- **cluster vm sweep, fix to only use managed vms**
When kubemacpool performs cluster sweeps for virtual machines (during
macPoolMap initalization for example), it needs to only consider the vms
from managed …
=> consider opt-mode when inserting vms/pod from the cluster to macPoolMap

doc/pod-creation-example.md, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/webhook/pod/pod.go
Currently, a pod cannot be created when managed with Kubemacpool (Issue #273), due to
an error in the patching procees of the webhook.
Fixed by patching the annotation needed.
```release-note
NONE
```
=> pod, Fix pod patching that causes the pod to error on creation

pkg/webhook/pod/pod.go, pkg/webhook/virtualmachine/virtualmachine.go
This PR adds more scenarios where the kuemacpool TS annotation is updated, 
but also making sue we do not cause an update loop.
Also, it fixes a problem with the way annotations where patched in the webhook handlers.
- **webhook, vm, Include metadata changes to kubemacpool TS update scenario**
Currently, only vm spec changes in the cause the kubemacpool
TransactionTimestampAnnotation to be updated. In order to optimize
updating of the mac to be faster, we also include metadata changes like
Annotation and namespace updates.
We do not include the TransactionTimestampAnnotation itself when
checking for changes, to avoid an internal update loop.
- **webhook, Fix Patching of annotations**
Currently update of the annotation patch causes other existing …
=> webhook, Include metadata changes to kubemacpool TS update scenario

pkg/manager/manager.go
This PR bumps apiextensions.k8s.io to v1
```release-note
bump apiextensions.k8s.io to v1
```
=> apiextensions, bump apiextensions.k8s.io to v1

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, tests/virtual_machines_test.go
This PR reduces kubemacpool's wait-time to 5 minutes, and adjusts tests accordingly to not be affected by webhook rejects.
- **reduce wait-time to 5 minutes**
currently if a webhook change is rejected then after wait-time
the kubemacpool goroutine will refresh the mac-entry after wait-time
according to what is set in the vm instance.
Reducing this value to 5 minutes, to allow quicker response time.
- **ci, extend test eventually timeout**
in tests that check webhook changes, we extend the timeout to ensure that
if the last webhook change was rejected, the mac entry will eventually get
refreshed with the persisted value.
```release-note
NONE
```
=> Reduce wait-time to 5 min

cluster/up.sh
sometimes automation tests fail on kubevirt not being ready.
increasing timeout to 360s, and by that aligning to [HCO](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/c8c49f989ab8ff5415dae8c4f1063fc08ff76963/tests/travis-tests/test.sh#L9).
```release-note
NONE
```
=> cluster-up, increase kubevirt timeout

go.mod, go.sum, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go, vendor/modules.txt
Bump kube-admission-webhook to [v0.15.0](https://github.com/qinqon/kube-admission-webhook/releases/tag/v0.15.0)
```release-note
Fix certificate rotation issue related to tls: pub key not matching private key
```
=> Bump kube-admission-webhook 0.15.0

cluster/up.sh
This PR changes the cluster-up script to deploy latest kubevirt v0.40 versions.
```release-note
NONE
```
=> bump cluster-up to follow kuvevirt v0.40

cluster/up.sh
As part of cluster-up, CNAO is deployed.
Bump the version of it, since some deprecated api versions
were fixed since the latest bump.
```release-note
None
```
=> cluster-up, Bump CNAO version

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
This PR removes the kubemacpool deployment memory limit, since we do not want to use limit memory on control-plane
components such as kubemacpool.
This commit also solves an issue found in BZ#1958108[0]
[0] https://bugzilla.redhat.com/show_bug.cgi?id=1958108
```release-note
NONE
```
=> [release-v0.21] limit, Remove limit from kubemacpool deployment

cluster/up.sh, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
This PR removes the kubemacpool deployment memory limit, since we do not want to use limit memory on control-plane
components such as kubemacpool.
This commit also solves an issue found in BZ#1958108[0]
[0] https://bugzilla.redhat.com/show_bug.cgi?id=1958108
```release-note
NONE
```
=> [release-v0.20] Remove kmp limits

pkg/pool-manager/macpoolmap.go, pkg/pool-manager/virtualmachine_pool.go
Currently, Kubemacpool logs often print the entire macPoolMap cache.
This may be too excessive for non-debug purposes, so refactoring the
logs accordingly
```release-note
NONE
```
=> logs, Refactor logs to remove macPoolMap on non-debug logs

cmd/manager/main.go, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, go.mod, go.sum, pkg/names/names.go, pkg/names/names_suite_test.go, pkg/names/names_test.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go, vendor/modules.txt
Bump Kaw to v0.16.0 in order to support relationship labels.
In order to have relationship (app.kubernetes.io/*)
on all deployed resources,
this commit adapts kubemacpool to use bumped kaw
which allows providing ExtraLabels field.
This way the secrets that are created by kaw
will be labeled with relationship labels.
```release-note
None
```
=> Relationship labels, Adapt to new kaw for secrets labeling

pkg/controller/virtualmachine/virtualmachine_controller.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/virtualmachine/virtualmachine.go, tests/tests.go, tests/virtual_machines_test.go
we no longer need to keep the vm instance until kubemacpool has freed
the vm macs from the pool since we now store the vm-name in the macpool
mac entry.
Hence, we should remove the finalizer from the vm creation.
For backwards compatibility, we still remove the finalizer if it exists
when deleting the vm.
```release-note
NONE
```
=> finalizer, remove kubemacpool finalizer

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Add system-cluster-critical to kubemacpool pods.
Since kmp pods aren't bound to a specific node,
yet those are important pods, assign system-cluster-critical
pc to them.
This will make the control plane less sensitive to preemption
than user workloads.
```release-note
None
```
=> control-plane, Add Priority class

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Manual Cherry-pick of https://github.com/k8snetworkplumbingwg/kubemacpool/pull/315
Add system-cluster-critical to kubemacpool pods.
Since kmp pods aren't bound to a specific node,
yet those are important pods, assign system-cluster-critical
pc to them.
This will make the control plane less sensitive to preemption
than user workloads.
```release-note
None
```
=> [release-v0.26] control-plane, Add Priority class

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Update `mac-controller-manager` minimum memory request according empiric measures,
in order to reduce idle usage and minimum required memory
for scheduling kubemacpool.
Update `cert-manager` cpu / memory requests according empiric use measures.
See https://bugzilla.redhat.com/show_bug.cgi?id=1935218
```release-note
None
```
=> Update resources requests

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
In order to allow the cert-manager to give faster SLA,
as the webhook (and handler) depends on it,
increase minimum CPU and memory requests.
See https://github.com/nmstate/kubernetes-nmstate/pull/781#discussion_r665255528
```release-note
None
```
=> cert-manager, Update minimum CPU request

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/gauges/gauges.go, pkg/pool-manager/virtualmachine_pool.go, tests/kubectl/kubectl.go, tests/virtual_machines_test.go
kubevirt_kmp_duplicate_macs counts how many duplicate macs
were found upon kubemacpool init.
Additional changes:
Improve log in case of Mac Address duplicates in order to ease mitigation.
```release-note
None
```
=> metrics, Add kubevirt_kmp_duplicate_macs gauge

pkg/webhook/pod/pod.go, pkg/webhook/virtualmachine/virtualmachine.go
DryRun pointer is optional, so it might be nil.
Fix the condition to support this case.
```release-note
None
```
=> dryRun, Fix logic conditions of dryRun

tests/tests.go
In order to make reading the logs easier,
shorten the vm / pods names from 32 random characters
to 5.
```release-note
None
```
=> tests, Create test vms and pods with shorter name

cluster/up.sh
Aligning to CNAO and kubevirt stable branches
```release-note
NONE
```
=> cluster-up, Bump CNAO and kubevirt to latest

pkg/controller/pod/pod_controller.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go, pkg/webhook/pod/pod.go, pkg/webhook/virtualmachine/virtualmachine.go, tests/virtual_machines_test.go
In case of "server" ("All" when used by controller runtime) dryRun, 
we do want to return an updated server response, 
which allocates Mac Address, but without doing side effects.
Fix the flow to support it.
Note that the Mac pool head is changed, so calling twice dryRun
won't yield the same Mac Address in the response.
It is needed because in case there are multiple Mac Addresses in
the same request, we should not give the same Mac even on dryRun,
hence the mac pool head should be updated.
```release-note
None
```
=> dryRun, Adapt VM Mac Address allocation to support dryRun

cluster/up.sh
This branch should follow kubevirt v0.41 branch
```release-note
NONE
```
=> [release-v0.26] kubevirt, bump kubevirt version to follow v0.41

cluster/up.sh
release-v0.21 branch should follow kubevirt v0.36 branch
```release-note
NONE
```
=> [release-v0.21] kubevirt, bump kubevirt version to follow v0.36

go.mod, go.sum, vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go, vendor/modules.txt
The kmp cert-manager was rotating certs not owned by it. This change
bump kube-admission-webhook to 0.18.0 to prevent that.
```release-note
Bump kube-admission-webhook to v0.18.0
```
=> deps: Bump kaw to 0.18.0

cluster/up.sh, config/default/manager/manager.yaml, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, tests/virtual_machines_test.go
KMP uses controller runtime which creates an http
end point for /metrics.
In order to support https, we deploy rbac-proxy container
in the same pod of KMP.
The new container exposes https end point,
and connects internally to the http end point.
It is self signed, and protected with rbac rules.
Will work offline with Oren Cohen in order to use sha instead of label for the rbac-proxy image.
It is needed for downstream.
```release-note
None
```
=> metrics: Use https instead of http

cluster/up.sh, config/default/manager/manager.yaml, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, tests/virtual_machines_test.go
This reverts commit 653c5e6bd3cf824b2aa2e5a92cd438ff2b21066b.
Reverting until we have a D/S solution for the rbac-proxy image
```release-note
None
```
=> Revert "metrics: Use https instead of http (#346)"

config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Kubemacpool is now using `kube-rbac-proxy`, but the manifests were not
updated accordingly.
Aligning manifests.
```release-note
NONE
```
=> config, Align kubemacpool manifest

automation/check-patch.unit-test.sh
In order to detect that we don't miss updating files,
with make generate, add make check to the unit tests job.
```release-note
None
```
=> unit tests: Add make check

go.mod, go.sum, vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server.go, vendor/modules.txt
/kind bug
The cipher suites names can be specified with OpenSSL format latest kaw
understand them too.
```release-note
Bump kube-admission-webhook v0.20.0 (Support OpenSSL CipherSuites names)
```
=> deps: Bump kaw to 0.20.0

cluster/up.sh
This PR bumps KMP devepement and test env  to run with latest stable CNAO and Kubevirt releases.
```release-note
NONE
```
=> ci, Bump CNAO and Kubevirt releases

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Currently if the node upon which KMP-manager deployment runs reboots,
the KMP pod is evicted only 5 minutes (default) after the node is unreachable.
Since KMP-manager deployment is is essential for VM create/update
service-ability, reducing this eviction to 1 minute. This is done by
altering the tolerations config [0]
This means that if the node is not available/ready for more than 1
minute, the pod will evict and will try to reschedule using the
configured affinity.
[0] https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
```release-note
Reduce Kubemacpool-manager node eviction timeout
```
=> manager, Reduce toleration in case of node reboot

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
We have to comply with the new Pod Security Admission from kubernetes v1.25, this change bump k8s to 1.25 to mark namespaces as "restricted" and fix manifests comply with it.
```release-note
Adapt to k8s 1.25 Pod Security Admission with "restricted" enforcement
```
=> psa: Adapt manifest to comply with "restricted"

go.mod
This PR bumps go to 1.18 as centos9 will not support go 1.17.
```release-note
NONE
```
=> go.mod: Bump go to 1.18

config/default/manager/manager.yaml, config/default/mutatepods_opt_out_patch.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, config/test/mutatepods_opt_mode_patch.yaml
Following https://github.com/kubevirt/cluster-network-addons-operator/pull/1145/files#r796372158
We don't need this label on KMP, and it require busy work on CNAO (see linked issue below).
Hence remove it from the namespace.
Note: the 2nd commit is manual removing from the files, where `make generate` didn't remove from.
See first bullet at https://github.com/kubevirt/cluster-network-addons-operator/issues/1567
```release-note
None
```
=> manifests: Remove control-plane label from namespace

.github/workflows, hack/check_hashicorp.sh
Validates that no hashicorp are used beside the whitelisted ones
(because they shifted to BSL license)
Atm no hashicorp is used, but lets protect in case someone will add.
Based on the whitelist that CNAO uses.
Need to validate git actions runs it on next PRs, as this is the first one.
(git actions is enabled)
```release-note
None
```
=> check hashicorp: Add hashicorp whitelist

cluster/up.sh
The logic to get latest z stream is outdated for v0.44 as the release file 
doesnt have full history for old versions. 
Fetch manually the latest z stream for the used version.
```release-note
None
```
=> [release-0.33] cluster-up: Fix kubevirt deploy

cluster/up.sh
The logic to get latest z stream is outdated for v0.44 as the release file
doesnt have full history for old versions.
Fetch manually the latest z stream for the used version.
```release-note
None
```
=> [release-v0.38] cluster-up: Fix kubevirt deploy

pkg/pool-manager/macentry_test.go, pkg/pool-manager/mackey.go, pkg/pool-manager/mackey_test.go, pkg/pool-manager/macpoolmap.go, pkg/pool-manager/macpoolmap_test.go, pkg/pool-manager/migratelegacyconfigmap.go, pkg/pool-manager/migratelegacyconfigmap_test.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, pkg/pool-manager/transaction.go, pkg/pool-manager/virtualmachine_pool.go, tests/virtual_machines_test.go
A macAddress can be specified with different separators:
- ":" e.g. "02:00:00:00:ff:ff"
- "-" e.g. "02-00-00-00-ff-ff"
- "." e.g. "0200.0000.ffff"
Currently, the duplicate mac check works only if the two compared mac address use the same separator.
The duplicate check is made looking at the existence of key of the macMap. The keys of the mapMap are the macAddress string.
With this commit, a `macKey` struct is introduced. The latter stores the normalized string of the macAddress and can be used as unique key and identifier of a macAddress.
Fixes https://issues.redhat.com/browse/CNV-30974
```release-note
Fix duplicate check with different mac address separator
```
=> Fix duplicate check with different mac format

cluster/up.sh
This PR bumps the kubevirt major and minor version deployed on cluster-up
```release-note
NONE
```
=> cluster-up: Bump kubevirt major-minor version to v1.2

cluster/up.sh
This PR bumps the kubevirt major and minor version deployed on cluster-up
```release-note
NONE
```
=> [release 0.42] cluster-up: Bump kubevirt major-minor version to v1.1

cluster/up.sh
This PR bumps the kubevirt major and minor version deployed on cluster-up
```release-note
NONE
```
=> [release-0.41] cluster-up: Bump kubevirt major-minor version to v1.0

cluster/up.sh
This PR bumps the kubevirt major and minor version deployed on cluster-up
```release-note
NONE
```
=> [release-0.40] cluster-up: Bump kubevirt major-minor version to v0.59

go.mod
This PR bumps the go version on the go.mod file, because the current go version (1.18) is [breaking](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_kubemacpool/419/pull-kubemacpool-unit-test-v0.39/1779370365357658112) our CI.
```release-note
NONE
```
=> [release-0.39] vendor, Bump go.mod go version to 1.19

go.mod
This PR bumps the go version on the go.mod file, because the current go version (1.18) is [breaking](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_kubemacpool/418/pull-kubemacpool-unit-test-v0.40/1779370301017034752) our CI.
```release-note
NONE
```
=> [release-0.40] vendor, Bump go.mod go version to 1.19

pkg/pool-manager/pool_test.go, pkg/pool-manager/virtualmachine_pool.go
This PR fixes a panic that occurs if a VM is created/updated with no template.
Although this field is mandatory, kubemacpool should not panic if it happens.
```release-note
Fix panic over nil template
```
=> pool-manager: Prevent panic if VM template is nil

cluster/cluster.sh, hack/bump-kubevirtci.sh
It is helpful either manually or for example
when used from CNAO, to use same tag of the cluster that CNAO deployed.
Otherwise a kubevirtci tag mismatch can cause failures once running 
KMP e2e tests from CNAO.
```release-note
None
```
=> cluster: Allow kubevirtci tag overriding

config/default/manager/manager.yaml, config/default/rbac/rbac_role_binding.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
Currently kubemacpool pods are using the default SA. Therefore extra permissions are being granted to the default SA.
It would be better if they will use a dedicated SA.
```release-note
NONE
```
=> rbac: Move to use private ServiceAccount

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh, go.mod
This PR bumps kubevirtci tag and provider to latest, and also bumps golang to `1.22.0`. 
```release-note
NONE
```
=> Bump dev dependencies

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
The origin-kube-rbac-proxy image is not compatible with the s390x architecture. This change deploys an image that is multi arch supported.
The origin-kube-rbac-proxy image is not compatible with the s390x architecture.
This change deploys an image that is multi arch supported(https://quay.io/repository/brancz/kube-rbac-proxy/manifest/sha256:e6a323504999b2a4d2a6bf94f8580a050378eba0900fd31335cf9df5787d9a9b).
proposed image(https://quay.io/repository/brancz/kube-rbac-proxy/manifest/sha256:e6a323504999b2a4d2a6bf94f8580a050378eba0900fd31335cf9df5787d9a9b) is built from parent repo of https://github.com/openshift/kube-rbac-proxy.
```release-note
None
```
=> feat: use multi arch supported image for kube-rbac-proxy.

doc/simple-vm.yaml, doc/vm-creation-example.md
The VM Running API is deprecated.
This PR replaces running API with RunStrategy API.
```release-note
NONE
```
=> docs: Remove VM Running API usage

Makefile
The IMAGE_GIT_TAG is generated using `git describe` to create a virtual
tag for the image, and used in order to tag every push to the repository
for later use.
However, when an actual git tag exists (e.g., v0.45.0), git describe
returns that tag. This behavior makes it possible to accidentally
overwrite push an existing version tag in the registry.
Flow Leading to the Issue:
1. A new kmp release is created, pushing a new tag (e.g., v0.45.0).
2. A stable branch is created from that commit, pushing a new stable
branch tag (e.g., release-0.45_latest).
2.1 . During this push, IMAGE_GIT_TAG resolves to this Git tag (e.g.,
v0.45.0) due to git describe.
2.2 Makefile attempts to push the image with this tag (e.g., v0.45.0) to
the registry, overwriting the …
=> Makefile, push: Prevent overwriting existing version tags

renovate.json
Renovate is a tool for bumping dependencies
Renovate will be used only for security patches for main and release-0.45 branch
```release-note
NONE
```
=> feat: Add renovate config

go.mod
This PR bumps to go1.22.11
```release-note
NONE
```
=> [release-0.44] vendor: Bump go1.22.11

renovate.json
This PR fixes supported branches on renovate: release-0.40 is not supported while release-0.39 is supported.
```release-note
NONE
```
=> renovate: Fix supported stable branches

cluster/up.sh
getLatestPatchVersion gets the kubevirt x.y version, and returns the latest z releases of kubevirt using github API. 
The default amount of releases outputted by github API is 30.
In order to allow fetching older kubevirt versions, expanding the list of kubevirt releaeses to the maximum pagination allowed [0]
[0] https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#changing-the-number-of-items-per-page
```release-note
NONE
```
=> cluster/up: Maximize kubevirt releases pagination per page

Makefile, go.mod
This PR sets the go.mod version to 1.20
```release-note
NONE
```
=> [release-0.42] go.mod, Makefile: Set go version to 1.20

Makefile, go.mod
This PR sets the go.mod version to 1.20
```release-note
NONE
```
=> [release-0.41] go.mod, Makefile: Set go version to 1.20

tests/tests_suite_test.go
logs are not printed correctly as shown on https://github.com/k8snetworkplumbingwg/kubemacpool/issues/452
This PR is fixing that
```release-note
NONE
```
=> e2e: Fix logging during test failure

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.45] Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.44] Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.43] Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.42] Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.41] Makefile: Enforce allowed go version

Makefile, go.mod, hack/check-go-version.sh, hack/check.sh
Notes:
```release-note
NONE
```
=> [release-0.39] Makefile: Enforce allowed go version

go.mod, go.sum, tests/tests.go, tests/virtual_machines_test.go, vendor/k8s.io/utils/clock/testing/fake_clock.go, vendor/k8s.io/utils/integer/integer.go, vendor/k8s.io/utils/net/multi_listen.go, vendor/k8s.io/utils/pointer/pointer.go, vendor/k8s.io/utils/ptr/OWNERS, vendor/k8s.io/utils/ptr/README.md, vendor/k8s.io/utils/ptr/ptr.go, vendor/k8s.io/utils/trace/trace.go, vendor/modules.txt
This PR fixed e2e infra that uses old kubevirt VM Running API.
```release-note
NONE
```
=> e2e: Change deprecated vm Running API

automation/check-patch.e2e-k8s.sh, automation/check-patch.setup.sh, tests/reporter/writers.go, tests/tests_suite_test.go
currently e2e test prints the logs to the screen.
This PR is moving the logs to be written to artifacts.
See [log artifacts example](https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_kubemacpool/535/pull-kubemacpool-e2e-k8s/1917123323125305344/artifacts/)
```release-note
NONE
```
=> tests, e2e: Log failed test.

go.mod
This PR sets the allowed go to 1.23 on the `release-0.47` stable branch
```release-note
NONE
```
=> [release-0.47] go.mod: Set allowed go version on stable branch

config/default/kustomization.yaml, config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/webhook/webhook.go
This add the readiness and liveness probes to the kubemacpool deployment containers
cert-manager is skip since that's not really a part of kubemacpool
```release-note
Add readiness and liveness probe to all the kubemacpool containers
```
=> manifests: Add readyness and liveness probes

cluster/sync.sh, config/default/kustomization.yaml, config/default/network-policy/allow-egress-dns.yaml, config/default/network-policy/allow-egress-kube-apiserver.yaml, config/default/network-policy/allow-ingress-to-kmp-service.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, hack/install-deny-all-net-pol.sh, tests/tests_suite_test.go
In a scenario where a cluster networking has been hardened and futures
a default deny-all network policy that affects kubemacpool namespace,
kubemacpool will not be able to operate properly.
This PR introduce network-policies for kubemacpool allowing kubemacpool to operate,
complying with restrictions in form of deny all network-policy.
In order to have coverage for the introduced network-policies, and additional deny-all network-policies is installed as part of the cluster-sync flow.
Having a deny-all network-policy installed, allow the introduced network-policies to be tested in a development and test environments, locally and CI.
```release-note
config: Introduce network-policies to enable …
```
=> Add NetworkPolicies

config/default/kustomization.yaml, config/default/network-policy/allow-ingress-to-metrics-endpoint.yaml, config/default/network-policy/allow-ingress-to-webhook.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml
When CNAO deploy kubemacpool, we see failures when prometheus stack fail to fire events that related to kubemacpool:
- When KMP detects duplicate macs, it doesn't fire KubeMacPoolDuplicateMacsFound 
- When CNAO deploy KMP it fire KubemacpoolDown, but kubemacpool pods are healthy.
Adding network-policy to allow ingress to kubemacpool metrics endpoint solve the issue, which was missing from the original PR #541 
This PR adds network-policy to allow ingress traffic to kubemacpool's metrics endpoint.
```release-note
NONE
```
=> Network policies: Allow ingress to metrics endpoint

pkg/pool-manager/pod_pool.go
This change make the pod initial looping faster by first checking if pods has no multus network (that's going to be 99% of the cases).
```release-note
make kubemacpool readiness faster by checking first multus network annotation existence.
```
=> pod-pool: skip if pod has no multus network

config/test/kubemacpool.yaml, config/test/kustomization.yaml, config/test/manager_range_patch.yaml, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, tests/virtual_machines_test.go
The scenario of full mac pool is not easy to recreate in a cluster with
a big range, and it could be easily replaced by a unit test.
This PR is 
- removing e2e tests that check same KMP functionality with full ip pool scenario.
- introducing a unit test to check full ip pool scenario.
- removing the range patch reducing the MAC range in tests manifest to the original size
```release-note
NONE
```
=> pool-manager: Refactor full ip pool e2e tests to unit test

go.mod, tests/tests_suite_test.go
This PR sets go version to 1.24 including the go version guard.
```release-note
set go to 1.24
```
=> go.mod: Set go to 1.24

config/default/manager/manager.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/virtualmachine_pool.go
Currently, initMap is taking a lot of time and API calls, that make startup time on big clusters (10k VMs) too long.
This PR is optimizing the InitMap by reading the supported namespaces before paginating through the pods. 
This reduces the startup time on big clusters from 6m+ to ~80s.
```
[root@e44-h32-000-r650 ~]# oc get vm -A | wc -l
10001
[root@e44-h32-000-r650 ~]# oc get pod -n openshift-cnv -w kubemacpool-mac-controller-manager-6bdfb65b45-f4s4r
NAME                                                  READY   STATUS    RESTARTS   AGE
kubemacpool-mac-controller-manager-6bdfb65b45-f4s4r   1/2     Running   0          14s
kubemacpool-mac-controller-manager-6bdfb65b45-f4s4r   2/2     Running   0          81s
```
This PR also increases the readiness timeout to 3m.
**What this PR does / why …
=> Optimize init map

Makefile, config/default/rbac/rbac_role.yaml, config/release/kubemacpool.yaml, config/test/kubemacpool.yaml, pkg/controller/add_configmap.go, pkg/controller/configmap/configmap_controller.go, pkg/controller/configmap/configmap_controller_test.go, pkg/controller/configmap/configmap_suite_test.go, pkg/manager/manager.go, pkg/names/names.go, pkg/pool-manager/pod_pool.go, pkg/pool-manager/pool.go, pkg/pool-manager/pool_test.go, tests/range_day2_test.go, tests/tests_suite_test.go
This PR adds a controller that watches the kubemacpool-mac-range configmap (where the ranges are set, and are extracted as env vars on the kubemacpool manager pod) and safely updates the new ranges.
In case of invalid range params inserted on day2, the controller will log the errors and will ignore the new suggested range. 
```release-note
Support day2 range changes
```
=> Support day2 range changes
